// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.account_purge_response")
public data class AccountPurgeResponse(
    /**
     * If the purge operation was succesfully started
     */
    public val initiated: Boolean? = false,
) : Response
