// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlin.Long
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.consumer_getnext_request")
public data class ConsumerGetnextRequest(
    /**
     * A duration from now when the pull should expire, stated in nanoseconds, 0 for no expiry
     */
    public val expires: Long? = null,
    /**
     * How many messages the server should deliver to the requestor
     */
    public val batch: Long? = null,
    /**
     * Sends at most this many bytes to the requestor, limited by consumer configuration max_bytes
     */
    @SerialName("max_bytes")
    public val maxBytes: Long? = null,
    /**
     * When true a response with a 404 status header will be returned when no messages are available
     */
    @SerialName("no_wait")
    public val noWait: Boolean? = null,
    /**
     * When not 0 idle heartbeats will be sent on this interval
     */
    @SerialName("idle_heartbeat")
    public val idleHeartbeat: Long? = null,
)
