// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.advisory.v1.consumer_action")
public data class ConsumerAction(
    public val type: String,
    /**
     * Unique correlation ID for this event
     */
    public val id: String,
    /**
     * The time this event was created in RFC3339 format
     */
    public val timestamp: String,
    /**
     * The action that the event describes
     */
    public val action: String,
    /**
     * The name of the Stream that the Consumer belongs to
     */
    public val stream: String,
    /**
     * The name of the Consumer that's acted on
     */
    public val consumer: String? = null,
)
