// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
@SerialName("io.nats.jetstream.api.v1.consumer_list_response")
public data class ConsumerListResponse(
    /**
     * Full Consumer information for each known Consumer
     */
    public val consumers: List<JsonObject>,
) : Response
