// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.consumer_leader_stepdown_response")
public data class ConsumerLeaderStepdownResponse(
    /**
     * If the leader successfully stood down
     */
    public val success: Boolean,
) : Response
