// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.metric.v1.consumer_ack")
public data class ConsumerAck(
    public val type: String,
    /**
     * Unique correlation ID for this event
     */
    public val id: String,
    /**
     * The time this event was created in RFC3339 format
     */
    public val timestamp: String,
    /**
     * The name of the stream where the message is stored
     */
    public val stream: String,
    /**
     * The name of the consumer where the message is held
     */
    public val consumer: String,
    /**
     * The sequence of the message in the stream that were acknowledged
     */
    @SerialName("stream_seq")
    public val streamSeq: Int,
    /**
     * The sequence of the message in the consumer that were acknowledged
     */
    @SerialName("consumer_seq")
    public val consumerSeq: Int,
    /**
     * The time it took on the final delivery for the message to be acknowledged in nanoseconds
     */
    @SerialName("ack_time")
    public val ackTime: Int,
    /**
     * The number of deliveries that were attempted before being acknowledged
     */
    public val deliveries: Int,
)
