// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.meta_leader_stepdown_request")
public data class MetaLeaderStepdownRequest(
    /**
     * Placement requirements for a stream
     */
    public val placement: Placement? = null,
) {
    @Serializable
    public data class Placement(
        /**
         * The desired cluster name to place the stream
         */
        public val cluster: String,
        /**
         * Tags required on servers hosting this stream
         */
        public val tags: List<String>? = null,
    )
}
