// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.meta_server_remove_request")
public data class MetaServerRemoveRequest(
    /**
     * The Name of the server to remove from the meta group
     */
    public val peer: String? = null,
    /**
     * Peer ID of the peer to be removed. If specified this is used instead of the server name
     */
    @SerialName("peer_id")
    public val peerId: String? = null,
)
