// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.ULong
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.pub_ack_response")
public data class PubAckResponse(
    public val error: Error? = null,
    /**
     * The name of the stream that received the message
     */
    public val stream: String,
    /**
     * If successful this will be the sequence the message is stored at
     */
    public val seq: ULong? = null,
    /**
     * Indicates that the message was not stored due to the Nats-Msg-Id header and duplicate
     * tracking
     */
    public val duplicate: Boolean? = false,
    /**
     * If the Stream accepting the message is in a JetStream server configured for a domain this
     * would be that domain
     */
    public val domain: String? = null,
) : Response {
    @Serializable
    public data class Error(
        /**
         * HTTP like error code in the 300 to 500 range
         */
        public val code: Int,
        /**
         * A human friendly description of the error
         */
        public val description: String? = null,
        /**
         * The NATS error code unique to each kind of error
         */
        @SerialName("err_code")
        public val errCode: Int? = null,
    )
}
