// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.advisory.v1.server_out_of_space")
public data class ServerOutOfSpace(
    public val type: String,
    /**
     * Unique correlation ID for this event
     */
    public val id: String,
    /**
     * The time this event was created in RFC3339 format
     */
    public val timestamp: String,
    /**
     * The Stream that triggered the out of space event
     */
    public val stream: String? = null,
    /**
     * The server name that ran out of space
     */
    public val server: String,
    /**
     * The server ID that ran out of space
     */
    @SerialName("server_id")
    public val serverId: String,
    /**
     * The cluster the server is in
     */
    public val cluster: String? = null,
)
