// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlin.ULong
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_msg_get_response")
public data class StreamMsgGetResponse(
    public val message: Message,
) : Response {
    @Serializable
    public data class Message(
        /**
         * The subject the message was originally received on
         */
        public val subject: String,
        /**
         * The sequence number of the message in the Stream
         */
        public val seq: ULong,
        /**
         * The base64 encoded payload of the message body
         */
        public val `data`: String? = null,
        /**
         * The time the message was received
         */
        public val time: String,
        /**
         * Base64 encoded headers for the message
         */
        public val hdrs: String? = null,
    )
}
