// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlin.Long
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_snapshot_request")
public data class StreamSnapshotRequest(
    /**
     * The NATS subject where the snapshot will be delivered
     */
    @SerialName("deliver_subject")
    public val deliverSubject: String,
    /**
     * When true consumer states and configurations will not be present in the snapshot
     */
    @SerialName("no_consumers")
    public val noConsumers: Boolean? = null,
    /**
     * The size of data chunks to send to deliver_subject
     */
    @SerialName("chunk_size")
    public val chunkSize: Long? = null,
    /**
     * Check all message's checksums prior to snapshot
     */
    public val jsck: Boolean? = false,
)
