// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlin.ULong
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_purge_response")
public data class StreamPurgeResponse(
    public val success: Boolean,
    /**
     * Number of messages purged from the Stream
     */
    public val purged: ULong,
) : Response
