// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_remove_peer_request")
public data class StreamRemovePeerRequest(
    /**
     * Server name of the peer to remove
     */
    public val peer: String,
)
