// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_info_request")
public data class StreamInfoRequest(
    /**
     * When true will result in a full list of deleted message IDs being returned in the info
     * response
     */
    @SerialName("deleted_details")
    public val deletedDetails: Boolean? = null,
    /**
     * When set will return a list of subjects and how many messages they hold for all matching
     * subjects. Filter is a standard NATS subject wildcard pattern.
     */
    @SerialName("subjects_filter")
    public val subjectsFilter: String? = null,
    /**
     * Paging offset when retrieving pages of subjet details
     */
    public val offset: Int? = null,
)
