// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_restore_response")
public data class StreamRestoreResponse(
    /**
     * The Subject to send restore chunks to
     */
    @SerialName("deliver_subject")
    public val deliverSubject: String,
) : Response
