// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_remove_peer_response")
public data class StreamRemovePeerResponse(
    /**
     * If the peer was successfully removed
     */
    public val success: Boolean,
) : Response
