// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlin.collections.List
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_list_response")
public data class StreamListResponse(
    /**
     * Full Stream information for each known Stream
     */
    public val streams: List<JsonObject>,
    /**
     * In clustered environments gathering Stream info might time out, this list would be a list of
     * Streams for which information was not obtainable
     */
    public val missing: List<String>? = null,
) : Response
