// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_names_request")
public data class StreamNamesRequest(
    /**
     * Limit the list to streams matching this subject filter
     */
    public val subject: String? = null,
    public val offset: Int? = null,
)
