// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.advisory.v1.stream_quorum_lost")
public data class StreamQuorumLost(
    public val type: String,
    /**
     * Unique correlation ID for this event
     */
    public val id: String,
    /**
     * The time this event was created in RFC3339 format
     */
    public val timestamp: String,
    /**
     * The name of the Stream that lost quorum
     */
    public val stream: String,
    public val replicas: Replicas,
) {
    @Serializable
    public data class Replicas(
        /**
         * The server name of the peer
         */
        public val name: String,
        /**
         * Indicates if the server is up to date and synchronised
         */
        public val current: Boolean,
        /**
         * Nanoseconds since this peer was last seen
         */
        public val active: Int,
        /**
         * Indicates the node is considered offline by the group
         */
        public val offline: Boolean? = false,
        /**
         * How many uncommitted operations this peer is behind the leader
         */
        public val lag: Int? = null,
    )
}
