// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_msg_get_request")
public data class StreamMsgGetRequest(
    /**
     * Stream sequence number of the message to retrieve, cannot be combined with last_by_subj
     */
    public val seq: Int? = null,
    /**
     * Retrieves the last message for a given subject, cannot be combined with seq
     */
    @SerialName("last_by_subj")
    public val lastBySubj: String? = null,
    /**
     * Combined with sequence gets the next message for a subject with the given sequence or higher
     */
    @SerialName("next_by_subj")
    public val nextBySubj: String? = null,
)
