// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.String
import kotlin.ULong
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.api.v1.stream_purge_request")
public data class StreamPurgeRequest(
    /**
     * Restrict purging to messages that match this subject
     */
    public val filter: String? = null,
    /**
     * Purge all messages up to but not including the message with this sequence. Can be combined
     * with subject filter but not the keep option
     */
    public val seq: ULong? = null,
    /**
     * Ensures this many messages are present after the purge. Can be combined with the subject
     * filter but not the sequence
     */
    public val keep: ULong? = null,
)
