// DO NOT EDIT THIS FILE! This was generated by the `./gradlew :generateJetStreamClasses` task.`
package nats.jetstream.protocol

import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("io.nats.jetstream.advisory.v1.terminated")
public data class Terminated(
    public val type: String,
    /**
     * Unique correlation ID for this event
     */
    public val id: String,
    /**
     * The time this event was created in RFC3339 format
     */
    public val timestamp: String,
    /**
     * The name of the stream where the message is stored
     */
    public val stream: String,
    /**
     * The name of the consumer where the message was terminated
     */
    public val consumer: String,
    /**
     * The sequence of the message in the stream that was terminated
     */
    @SerialName("stream_seq")
    public val streamSeq: String,
    /**
     * The sequence of the message in the consumer that was terminated
     */
    @SerialName("consumer_seq")
    public val consumerSeq: String,
    /**
     * The number of deliveries that were attempted
     */
    public val deliveries: Int,
)
